# Generated by Django 3.1 on 2023-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameannotation',
            name='page',
            field=models.TextField(blank=True, max_length=520, null=True),
        ),
        migrations.AlterField(
            model_name='nameannotation',
            name='kind',
            field=models.CharField(choices=[('', ''), ('note', 'note without photo'), ('photo', 'photo'), ('sample', 'to sample'), ('check', 'relocate'), ('invasive_link', 'invasive link')], max_length=50),
        ),
    ]
